# Generated by Django 5.1 on 2024-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='text',
        ),
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
