# Generated by Django 5.1 on 2024-09-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images/'),
        ),
    ]
