# Generated by Django 5.1 on 2024-09-20 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField(default='')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to='pages.pages')),
            ],
        ),
        migrations.DeleteModel(
            name='PageImage',
        ),
    ]
