# Generated by Django 5.1 on 2024-08-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pages_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
