# Generated by Django 5.1 on 2024-09-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_characterinformation_delete_pageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterinformation',
            old_name='subtitle',
            new_name='character_information',
        ),
    ]
