# Generated by Django 5.1 on 2024-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
