# Generated by Django 5.1 on 2024-08-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_details_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='slug',
        ),
    ]
